services:
  - name: frontend
    type: static_site
    env: static
    port: 3000  # Default port for React apps
    buildCommand: "cd frontend && npm install && npm run build && npm run copy-static-files"
    publishDir: "frontend/dist"
    envVars:
      - key: VITE_API_URL
        value: "your_db_url"  # Update to your backend URL
        
  - name: backend
    type: web
    env: python
    plan: free
    port: 8000  # Default port for Django
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic"
    startCommand: "cd backend && gunicorn backend.wsgi:application"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: your-database-name  # This automatically references the database
      - key: DB_USER
        value: "your_database_user"  # Or set in the dashboard
      - key: DB_PASSWORD
        value: "your_database_password"  # Or set in the dashboard
      - key: SECRET_KEY
        value: "your_secret_key"  # Set in the dashboard
      - key: DJANGO_ALLOWED_HOSTS
        value: "your-backend-url.onrender.com"
      - key: DB_NAME
        value: "your_db_name"
      - key: DB_PORT
        value: "your_db_port"
    healthCheckPath: "/api/health/"
    healthCheckInterval: 5
    healthCheckTimeout: 2
    healthCheckSuccessThreshold: 2
    healthCheckFailureThreshold: 3
    networkVisibility: public  # Can be 'public' or 'private'
    context: "/"  # Optional context path for your backend