services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: your-database-name  # This automatically references the database
      - key: DB_USER
        value: "your_database_user"  # Or set in the dashboard
      - key: DB_PASSWORD
        value: "your_database_password"  # Or set in the dashboard
      - key: DJANGO_SECRET_KEY
        value: "your_secret_key"  # Set in the dashboard
      - key: DJANGO_ALLOWED_HOSTS
        value: "your-backend-url.onrender.com"

  - type: static
    name: react-frontend
    buildCommand: "cd frontend && npm install && npm run build"
    publishPath: dist
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://your-backend-url.onrender.com/api"